spring.main.web-application-type=none

# Shared JPA configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.enable-lazy-load-no-trans=true

# Default profile (if none specified)
spring.profiles.active=postgres