# MySQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/learnquest_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# Initialize database from scripts
spring.datasource.initialization-mode=always
spring.datasource.schema=classpath:schema-postgres.sql
spring.datasource.data=classpath:data.sql

# Logging
logging.level.org.springframework.jdbc.datasource.init=DEBUG
