CREATE TABLE IF NOT EXISTS STUDENT
(
    STUDENTID  BIGINT GENERATED ALWAYS AS IDENTITY,
    FIRSTNAME  VARCHAR(40) NOT NULL,
    LASTNAME   VARCHAR(10) NOT NULL,
    DEPARTMENT VARCHAR(10) NOT NULL,
    FEES       DECIMAL(10, 2),
    VERSION    BIGINT,
    PRIMARY KEY (STUDENTID)
);

CREATE TABLE IF NOT EXISTS COURSE
(
    COURSEID  BIGINT GENERATED ALWAYS AS IDENTITY,
    STUDENTID BIGINT NOT NULL,
    TITLE     VARCHAR(40) NOT NULL,
    LOCATION  VARCHAR(40) NOT NULL,
    VERSION   BIGINT,
    PRIMARY KEY (COURSEID),
    CONSTRAINT FK_COURSE_STUDENT
        FOREIGN KEY (STUDENTID)
            REFERENCES STUDENT (STUDENTID)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE
(
    EMPLOYEEID BIGINT GENERATED ALWAYS AS IDENTITY,
    FIRSTNAME  VARCHAR(40) NOT NULL,
    LASTNAME   VARCHAR(10) NOT NULL,
    COMPANY    VARCHAR(30) NOT NULL,
    HOURLYRATE DECIMAL(10, 2),
    VERSION    BIGINT,
    PRIMARY KEY (EMPLOYEEID)
);

CREATE TABLE IF NOT EXISTS QUALIFICATION
(
    QUALIFICATIONID BIGINT GENERATED ALWAYS AS IDENTITY,
    EMPLOYEEID      BIGINT NOT NULL,
    TYPE            VARCHAR(10) NOT NULL,
    TITLE           VARCHAR(40) NOT NULL,
    INSTITUTION     VARCHAR(30) NOT NULL,
    VERSION         BIGINT,
    PRIMARY KEY (QUALIFICATIONID),
    CONSTRAINT FK_QUALIFICATION_EMPLOYEE
        FOREIGN KEY (EMPLOYEEID)
            REFERENCES EMPLOYEE (EMPLOYEEID)
);