CREATE TABLE STUDENT
(
    STUDENTID  BIGINT      NOT NULL AUTO_INCREMENT,
    FIRSTNAME  VARCHAR(40) NOT NULL,
    LASTNAME   VARCHAR(10) NOT NULL,
    DEPARTMENT VARCHAR(10) NOT NULL,
    FEES       DECIMAL(10, 2),
    VERSION    BIGINT,
    PRIMARY KEY (STUDENTID)
);

CREATE TABLE COURSE
(
    COURSEID  BIGINT      NOT NULL AUTO_INCREMENT,
    STUDENTID BIGINT      NOT NULL,
    TITLE     VARCHAR(40) NOT NULL,
    LOCATION  VARCHAR(40) NOT NULL,
    VERSION   BIGINT,
    PRIMARY KEY (COURSEID),
    CONSTRAINT FK_COURSE_STUDENT
        FOREIGN KEY (STUDENTID)
            REFERENCES STUDENT (STUDENTID)
);

CREATE TABLE EMPLOYEE
(
    EMPLOYEEID BIGINT      NOT NULL AUTO_INCREMENT,
    FIRSTNAME  VARCHAR(40) NOT NULL,
    LASTNAME   VARCHAR(10) NOT NULL,
    COMPANY    VARCHAR(30) NOT NULL,
    HOURLYRATE DECIMAL(10, 2),
    VERSION    BIGINT,
    PRIMARY KEY (EMPLOYEEID)
);

CREATE TABLE QUALIFICATION
(
    QUALIFICATIONID BIGINT      NOT NULL AUTO_INCREMENT,
    EMPLOYEEID      BIGINT      NOT NULL,
    TYPE            VARCHAR(10) NOT NULL,
    TITLE           VARCHAR(40) NOT NULL,
    INSTITUTION     VARCHAR(30) NOT NULL,
    VERSION         BIGINT,
    PRIMARY KEY (QUALIFICATIONID),
    CONSTRAINT FK_QUALIFICATION_EMPLOYEE
        FOREIGN KEY (EMPLOYEEID)
            REFERENCES EMPLOYEE (EMPLOYEEID)
);